### ISSUE TITLE
aborted repository loadings cause future exceptions

### ISSUE THREAD

**Issue by pridkett** [pridkett/gitminer#13]
If you've tried to load a repository in the past and there is an incomplete copy of the repository stored in /tmp/repo_loader then you'll get exceptions that cause the program to die. This should be resolved:

22:55:27 [main] INFO edu.unl.cse.git.AppMain AppMain.java:52 - Loading Repository: mojombo/jekyll
22:55:27 [main] INFO edu.unl.cse.git.BlueprintsDriver BlueprintsDriver.java:68 - Save Repository: mojombo/jekyll
22:55:27 [main] ERROR edu.unl.cse.git.RepositoryLoader RepositoryLoader.java:60 - Exception encountered opening repository:
java.io.IOException: Unknown repository format "null"; expected "0".
    at org.eclipse.jgit.storage.file.FileRepository.<init>(FileRepository.java:185) ~[org.eclipse.jgit-1.1.0.201109151100-r.jar:1.1.0.201109151100-r]
    at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:529) ~[org.eclipse.jgit-1.1.0.201109151100-r.jar:1.1.0.201109151100-r]
    at org.eclipse.jgit.api.Git.open(Git.java:112) ~[org.eclipse.jgit-1.1.0.201109151100-r.jar:1.1.0.201109151100-r]
    at org.eclipse.jgit.api.Git.open(Git.java:96) ~[org.eclipse.jgit-1.1.0.201109151100-r.jar:1.1.0.201109151100-r]
    at edu.unl.cse.git.RepositoryLoader.updateRepository(RepositoryLoader.java:55) [github-0.1-SNAPSHOT.jar:na]
    at edu.unl.cse.git.RepositoryLoader.getRepository(RepositoryLoader.java:36) [github-0.1-SNAPSHOT.jar:na]
    at edu.unl.cse.git.RepositoryLoader.getCommits(RepositoryLoader.java:67) [github-0.1-SNAPSHOT.jar:na]
    at edu.unl.cse.git.AppMain.main(AppMain.java:55) [github-0.1-SNAPSHOT.jar:na]
    at edu.unl.cse.git.App.run(App.java:64) [github-0.1-SNAPSHOT.jar:na]
    at edu.unl.cse.git.App.main(App.java:30) [github-0.1-SNAPSHOT.jar:na]
Exception in thread "main" java.lang.NullPointerException
    at edu.unl.cse.git.RepositoryLoader.getCommits(RepositoryLoader.java:67)
    at edu.unl.cse.git.AppMain.main(AppMain.java:55)
    at edu.unl.cse.git.App.run(App.java:64)
    at edu.unl.cse.git.App.main(App.java:30)

**Comment by pridkett** [comment]
@jurgns you should look at this.

**Comment by niels** [comment]
There's also a NoHeadException that may be raised if imports are aborted early on. The workaround is to delete /tmp/repo_loader.
