### ISSUE TITLE
args4j Maven Build Error

### ISSUE THREAD

**Issue by carlsonp** [pridkett/gitminer#24]
Hello.  I'm guessing I'm missing something simple here but in trying to build Gitminer using maven (Gremlin built with no errors):

mvn -e clean compile package

I get the following error:

```[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: args4j:args4j-site:pom:2.0.18

Reason: Cannot find parent: org.kohsuke:pom for project: args4j:args4j-site:pom:2.0.18 for project args4j:args4j-site:pom:2.0.18

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'args4j:args4j:jar': Cannot find parent: org.kohsuke:pom for project: args4j:args4j-site:pom:2.0.18 for project args4j:args4j-site:pom:2.0.18
  args4j:args4j:jar:2.0.18

from the specified remote repositories:
  jgit-repository (http://download.eclipse.org/jgit/maven),
  central (http://repo1.maven.org/maven2),
  jenkins-repository (http://maven.jenkins-ci.org:8081/content/repositories/releases/),
  wagstrom-net-external_free (http://patrick.wagstrom.net/maven/external_free)

Path to dependency: 
    1) net.wagstrom.research:github:jar:0.2-SNAPSHOT

```
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:711)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'args4j:args4j:jar': Cannot find parent: org.kohsuke:pom for project: args4j:args4j-site:pom:2.0.18 for project args4j:args4j-site:pom:2.0.18
  args4j:args4j:jar:2.0.18

from the specified remote repositories:
  jgit-repository (http://download.eclipse.org/jgit/maven),
  central (http://repo1.maven.org/maven2),
  jenkins-repository (http://maven.jenkins-ci.org:8081/content/repositories/releases/),
  wagstrom-net-external_free (http://patrick.wagstrom.net/maven/external_free)

Path to dependency: 
    1) net.wagstrom.research:github:jar:0.2-SNAPSHOT

```
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:430)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:74)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:316)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:304)
at org.apache.maven.plugin.DefaultPluginManager.resolveTransitiveDependencies(DefaultPluginManager.java:1499)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:442)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more
```

Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException: Unable to read the metadata file for artifact 'args4j:args4j:jar': Cannot find parent: org.kohsuke:pom for project: args4j:args4j-site:pom:2.0.18 for project args4j:args4j-site:pom:2.0.18
    at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:200)
    at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedArtifact(MavenMetadataSource.java:94)
    at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:387)
    ... 23 more
Caused by: org.apache.maven.project.ProjectBuildingException: Cannot find parent: org.kohsuke:pom for project: args4j:args4j-site:pom:2.0.18 for project args4j:args4j-site:pom:2.0.18
    at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1396)
    at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1407)
    at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:823)
    at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:255)
    at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:163)
    ... 25 more
Caused by: org.apache.maven.project.InvalidProjectModelException: Not a v4.0.0 POM. for project org.kohsuke:pom at /home/carlsonp/.m2/repository/org/kohsuke/pom/1/pom-1.pom
    at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1599)
    at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1571)
    at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:562)
    at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1392)
    ... 29 more
[INFO] ------------------------------------------------------------------------```

The file: /home/carlsonp/.m2/repository/org/kohsuke/pom/1/pom-1.pom

Contains a 301 Moved Permanently.  Could this be related to Issue: #23?

Thanks in advance.

**Comment by pridkett** [comment]
I think that I fixed this. The problem was with the jenkins maven repository. I've switched args4j to a version that is in the main maven repository.
