### ISSUE TITLE
Program crashes when repository lacks issues

### ISSUE THREAD

**Issue by pridkett** [pridkett/gitminer#3]
When a repository lacks issues the v3 scraper dies. This is the case that is found with ruby/ruby.

23:51:59 [main] TRACE n.w.research.github.RepositoryMiner RepositoryMiner.java:37 - Fetching repository: ruby/ruby
23:51:59 [main] DEBUG n.w.research.github.RepositoryMiner RepositoryMiner.java:39 - Fetched repository: ruby/ruby
23:51:59 [main] ERROR n.w.research.github.v3.IssueMinerV3 IssueMinerV3.java:33 - IOException in getOpenIssues ruby ruby
java.io.IOException: Gone
        at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:429) ~[org.eclipse.egit.github.core-1.2.0.jar:na]
        at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:514) ~[org.eclipse.egit.github.core-1.2.0.jar:na]
        at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:170) ~[org.eclipse.egit.github.core-1.2.0.jar:na]
        at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:136) ~[org.eclipse.egit.github.core-1.2.0.jar:na]
        at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:120) ~[org.eclipse.egit.github.core-1.2.0.jar:na]
        at org.eclipse.egit.github.core.service.IssueService.getIssues(IssueService.java:363) ~[org.eclipse.egit.github.core-1.2.0.jar:na]
        at net.wagstrom.research.github.v3.IssueMinerV3.getOpenIssues(IssueMinerV3.java:31) [github-0.1-SNAPSHOT.jar:na]
        at net.wagstrom.research.github.v3.IssueMinerV3.getAllIssues(IssueMinerV3.java:50) [github-0.1-SNAPSHOT.jar:na]
        at net.wagstrom.research.github.GitHubMain.main(GitHubMain.java:160) [github-0.1-SNAPSHOT.jar:na]
        at net.wagstrom.research.github.Github.run(Github.java:89) [github-0.1-SNAPSHOT.jar:na]
        at net.wagstrom.research.github.Github.main(Github.java:53) [github-0.1-SNAPSHOT.jar:na]
Exception in thread "main" java.lang.IllegalStateException: Invalid use of SingleClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
        at org.apache.http.impl.conn.SingleClientConnManager.getConnection(SingleClientConnManager.java:216)
        at org.apache.http.impl.conn.SingleClientConnManager$1.getConnection(SingleClientConnManager.java:190)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:401)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
        at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:501)
        at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:170)
        at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:136)
        at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:120)
        at org.eclipse.egit.github.core.service.IssueService.getIssues(IssueService.java:363)
        at net.wagstrom.research.github.v3.IssueMinerV3.getClosedIssues(IssueMinerV3.java:42)
        at net.wagstrom.research.github.v3.IssueMinerV3.getAllIssues(IssueMinerV3.java:51)
        at net.wagstrom.research.github.GitHubMain.main(GitHubMain.java:160)
        at net.wagstrom.research.github.Github.run(Github.java:89)
        at net.wagstrom.research.github.Github.main(Github.java:53)

**Comment by pridkett** [comment]
Current stable version of org.eclipse.egit.github.core does not read the output stream on errors.

For reference see: http://stackoverflow.com/questions/4612573/exception-using-httprequest-execute-invalid-use-of-singleclientconnmanager-c

This has been corrected in 1.3.0-SNAPSHOT. I've created a repo for a working version of the snapshot and added in the appropriate checks in the to handle nulls.

Fixed in: 3deebbebc8f3fe0938b5fdee6ac0e72c9728d0ac
