### ISSUE TITLE
 Git Repository loading functionality causing RuntimeException

### ISSUE THREAD

**Issue by prga** [pridkett/gitminer#35]
When using the repository loader command I get the following error:

~/src/gitminer$ ./repository_loader.sh -c configuration.properties
10:45:32.194 [main] DEBUG edu.unl.cse.git.App - Attempting to read properties file: configuration.properties
10:45:32.435 [main] DEBUG c.i.r.govsci.graph.BlueprintsBase - Requested database: neo4j url: test.graph.db
10:45:32.435 [main] INFO  c.i.r.govsci.graph.BlueprintsBase - Opening neo4j graph at: test.graph.db
Exception in thread "main" java.lang.RuntimeException: Format specifier 's'
    at com.tinkerpop.blueprints.impls.neo4j.Neo4jGraph.<init>(Neo4jGraph.java:163)
    at com.tinkerpop.blueprints.impls.neo4j.Neo4jGraph.<init>(Neo4jGraph.java:127)
    at com.ibm.research.govsci.graph.BlueprintsBase.<init>(BlueprintsBase.java:94)
    at net.wagstrom.research.github.BlueprintsDriver.<init>(BlueprintsDriver.java:122)
    at edu.unl.cse.git.CommitBlueprintsDriver.<init>(CommitBlueprintsDriver.java:32)
    at edu.unl.cse.git.AppMain.connectToGraph(AppMain.java:49)
    at edu.unl.cse.git.AppMain.main(AppMain.java:86)
    at edu.unl.cse.git.App.run(App.java:62)
    at edu.unl.cse.git.App.main(App.java:29)
Caused by: java.util.MissingFormatArgumentException: Format specifier 's'
    at java.util.Formatter.format(Formatter.java:2487)
    at java.util.Formatter.format(Formatter.java:2423)
    at org.neo4j.graphdb.factory.GraphDatabaseSetting.illegalValue(GraphDatabaseSetting.java:808)
    at org.neo4j.graphdb.factory.GraphDatabaseSetting.illegalValue(GraphDatabaseSetting.java:801)
    at org.neo4j.graphdb.factory.GraphDatabaseSetting$NumberOfBytesSetting.validate(GraphDatabaseSetting.java:599)
    at org.neo4j.graphdb.factory.GraphDatabaseSetting.validate(GraphDatabaseSetting.java:760)
    at org.neo4j.kernel.configuration.ConfigurationValidator.validate(ConfigurationValidator.java:50)
    at org.neo4j.kernel.configuration.Config.applyChanges(Config.java:125)
    at org.neo4j.kernel.InternalAbstractGraphDatabase.create(InternalAbstractGraphDatabase.java:265)
    at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:223)
    at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:79)
    at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:70)
    at com.tinkerpop.blueprints.impls.neo4j.Neo4jGraph.<init>(Neo4jGraph.java:151)
    ... 8 more

My configuration.properties looks like this:

et.wagstrom.research.github.login=
net.wagstrom.research.github.password=
net.wagstrom.research.github.email=

net.wagstrom.research.github.dbengine=neo4j
net.wagstrom.research.github.dburl=test.graph.db

net.wagstrom.research.github.projects=pridkett/gitminer

net.wagstrom.research.github.token=

edu.unl.cse.git.dbengine=neo4j
edu.unl.cse.git.dburl=test.graph.db
edu.unl.cse.git.repositories=pridkett/gitminer

**Comment by prga** [comment]
Hello @pridkett, 

even though I couldn't run the gitminer via sh scripts I was able to execute it directly from eclipse.

Thanks!
